import { NextResponse } from 'next/server';
const USDA_API='https://api.nal.usda.gov/fdc/v1/foods/search';
const item=(name,brand,cal,protein,carbs,fat,source,sourceUrl,confidence='High',extra={})=>({name,brand,cal,protein,carbs,fat,source,sourceUrl,confidence,...extra});
const MCD_SOURCE="McDonald's official nutrition";
const MCD={mcgriddle:item('Sausage, Egg & Cheese McGriddles',"McDonald's",550,20,47,28,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/sausage-egg-cheese-mcgriddles.html'),refresher:item('Medium Strawberry Watermelon Refresher',"McDonald's",210,0,49,0,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/strawberry-watermelon-refresher-medium.html'),nuggets4:item('4 Piece Chicken McNuggets',"McDonald's",170,9,10,10,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/chicken-mcnuggets-4-piece.html'),smallFries:item('Small World Famous Fries',"McDonald's",230,3,31,11,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/small-french-fries.html')};
const HEB_SOURCE='H-E-B official product nutrition';
const HEB={
 lemonSalmon:item('Meal Simple by H-E-B Lemon Pepper Salmon, Wild Rice & Broccoli','Meal Simple by H-E-B',510,36,35,25,HEB_SOURCE,'https://www.heb.com/product-detail/meal-simple-by-h-e-b-lemon-pepper-salmon-wild-rice-broccoli/2644047','High',{servingSize:'1 tray (359g)',productId:'2644047'}),
 chickenFettuccine:item('Meal Simple by H-E-B Chicken Fettuccine Alfredo Bowl','Meal Simple by H-E-B',690,39,70,28,HEB_SOURCE,'https://www.heb.com/product-detail/meal-simple-by-h-e-b-chicken-fettuccine-alfredo-bowl/2586002','High',{servingSize:'1 bowl (340g)',productId:'2586002'})
};
const WINGSTOP_SOURCE='Wingstop official nutrition guide',WINGSTOP_URL='https://s3.amazonaws.com/wingstop.com/assets/static/WSR18-0009-Corporate-NutritionalGuide-JumboWings-HR_OFFICAL.pdf';
const WS_SANDWICHES={plain:item('Chicken Sandwich - Plain','Wingstop',610,32,66,24,WINGSTOP_SOURCE,WINGSTOP_URL),atomic:item('Chicken Sandwich - Atomic','Wingstop',650,33,74,24,WINGSTOP_SOURCE,WINGSTOP_URL),cajun:item('Chicken Sandwich - Cajun','Wingstop',640,33,70,25,WINGSTOP_SOURCE,WINGSTOP_URL),'garlic parmesan':item('Chicken Sandwich - Garlic Parmesan','Wingstop',890,34,71,52,WINGSTOP_SOURCE,WINGSTOP_URL),hawaiian:item('Chicken Sandwich - Hawaiian','Wingstop',710,33,90,24,WINGSTOP_SOURCE,WINGSTOP_URL),'hickory smoked bbq':item('Chicken Sandwich - Hickory Smoked BBQ','Wingstop',730,34,96,24,WINGSTOP_SOURCE,WINGSTOP_URL),'lemon pepper':item('Chicken Sandwich - Lemon Pepper','Wingstop',850,32,67,50,WINGSTOP_SOURCE,WINGSTOP_URL),'louisiana rub':item('Chicken Sandwich - Louisiana Rub','Wingstop',790,32,67,43,WINGSTOP_SOURCE,WINGSTOP_URL),'mango habanero':item('Chicken Sandwich - Mango Habanero','Wingstop',740,32,94,24,WINGSTOP_SOURCE,WINGSTOP_URL),mild:item('Chicken Sandwich - Mild','Wingstop',870,32,67,52,WINGSTOP_SOURCE,WINGSTOP_URL),'original hot':item('Chicken Sandwich - Original Hot','Wingstop',630,32,68,25,WINGSTOP_SOURCE,WINGSTOP_URL),'spicy korean q':item('Chicken Sandwich - Spicy Korean Q','Wingstop',720,34,90,24,WINGSTOP_SOURCE,WINGSTOP_URL)};
const WS_FRIES=item('Seasoned Fries - Regular','Wingstop',500,8,69,21,WINGSTOP_SOURCE,WINGSTOP_URL),WS_RANCH=item('Ranch Dip','Wingstop',320,1,2,34,WINGSTOP_SOURCE,WINGSTOP_URL);
function nutrient(food,names){for(const n of food.foodNutrients||[]){const name=String(n.nutrientName||'').toLowerCase();if(names.some(x=>name.includes(x)))return Number(n.value||0)}return 0}
async function usda(query){const url=`${USDA_API}?api_key=${process.env.USDA_API_KEY||'DEMO_KEY'}&query=${encodeURIComponent(query)}&pageSize=10`;const res=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!res.ok)return null;const data=await res.json(),foods=data.foods||[];if(!foods.length)return null;const food=foods[0];return item(food.description,food.brandOwner||food.brandName||'USDA',Math.round(nutrient(food,['energy'])),Math.round(nutrient(food,['protein'])),Math.round(nutrient(food,['carbohydrate'])),Math.round(nutrient(food,['total lipid','total fat'])),'USDA FoodData Central',`https://fdc.nal.usda.gov/fdc-app.html#/food-details/${food.fdcId}/nutrients`,'Medium',{fdcId:food.fdcId})}
function cleanText(q){return q.toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').trim()} function has(q,...terms){return terms.some(t=>q.includes(t))}
function wingstopFlavor(q){const aliases=[['garlic parmesan',['garlic parmesan','garlic parm']],['hickory smoked bbq',['hickory smoked bbq','hickory bbq','bbq']],['lemon pepper',['lemon pepper']],['louisiana rub',['louisiana rub']],['mango habanero',['mango habanero']],['original hot',['original hot']],['spicy korean q',['spicy korean q','korean q']],['atomic',['atomic']],['cajun',['cajun']],['hawaiian',['hawaiian']],['mild',['mild']],['plain',['plain','no sauce','unseasoned']]];for(const [key,words] of aliases)if(words.some(w=>q.includes(w)))return key;return null}
function parseKnown(q){const low=cleanText(q),items=[],notes=[],clarifications=[];
 if(/sausage.*egg.*cheese.*mcgriddle|sausage egg and cheese mcgriddle|mcgriddle/.test(low))items.push(MCD.mcgriddle);if(/strawberry.*watermelon.*refresher/.test(low))items.push(MCD.refresher);if(/(?:4|four)[ -]?(?:piece|pc)?\s*(?:chicken\s*)?(?:mcnuggets|nuggets)/.test(low))items.push(MCD.nuggets4);if(/small\s+(?:world famous\s+)?(?:fry|fries)|(?:fry|fries)\s*(?:small)/.test(low))items.push(MCD.smallFries);
 // Verified H-E-B Meal Simple meals. Match the meaningful product words instead of trusting the first catalog result.
 if((has(low,'heb','h-e-b','meal simple')||has(low,'wild rice','fettuccine alfredo')) && has(low,'lemon pepper','lemon-pepper') && has(low,'salmon') && (has(low,'wild rice')||has(low,'broccoli'))) items.push(HEB.lemonSalmon);
 if((has(low,'heb','h-e-b','meal simple')||has(low,'microwavable','microwave')) && has(low,'chicken') && has(low,'alfredo') && has(low,'fettuccine','fettuccini')) items.push(HEB.chickenFettuccine);
 if(low.includes('wingstop')){const sandwichMention=has(low,'chicken sandwich','sandwich');if(sandwichMention){const flavor=wingstopFlavor(low);if(flavor)items.push(WS_SANDWICHES[flavor]);else{items.push({...WS_SANDWICHES.plain,confidence:'Medium',assumption:'No Wingstop flavor was specified, so this was logged as Plain.'});notes.push('Wingstop sandwich flavor changes calories a lot. Logged Plain because no flavor was specified.')}}if(has(low,'fries','seasoned fries','lemon pepper fries'))items.push(WS_FRIES);if(has(low,'ranch','ranch dip'))items.push(WS_RANCH);if(low.includes('combo')&&!has(low,'fries','seasoned fries'))items.push(WS_FRIES)}return{items,notes,clarifications}}
function isHeb(q){return /\b(h[ -]?e[ -]?b|heb|meal simple)\b/i.test(q)}
function meaningfulWords(s){const stop=new Set(['meal','simple','heb','h','e','b','from','with','and','the','had','ate','got','bought','some','today','microwavable','microwave']);return cleanText(s).replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>2&&!stop.has(w))}
function hebSearchTerms(q){return q.replace(/\b(i\s+(had|ate|got|bought)|i just (had|ate|got|bought)|from|at|an?|the|some|today|then)\b/gi,' ').replace(/\b(h[ -]?e[ -]?b|heb)\b/gi,' ').replace(/\s+/g,' ').trim()}
function scoreTitle(title,query){const t=cleanText(title);const words=meaningfulWords(query);return words.reduce((n,w)=>n+(t.includes(w)?1:0),0)}
async function hebLookup(query){const terms=hebSearchTerms(query),searchUrl=`https://www.heb.com/search/?q=${encodeURIComponent(terms)}`;try{const r=await fetch(searchUrl,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html'},cache:'no-store'});if(r.ok){const html=await r.text();const links=[...new Set([...html.matchAll(/href=["']([^"']*\/product-detail\/[^"']+)["']/gi)].map(m=>new URL(m[1],'https://www.heb.com').href))].slice(0,10);let best=null;for(const productUrl of links){try{const p=await fetch(productUrl,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html'},cache:'no-store'});if(!p.ok)continue;const h=await p.text();const title=(h.match(/<title>(.*?)<\/title>/i)?.[1]||'').replace(/ - Shop[\s\S]*$/i,'').trim();const score=scoreTitle(title,terms);if(!best||score>best.score)best={score,title,h,productUrl}}catch{}}if(best&&best.score>=Math.min(2,meaningfulWords(terms).length)){const text=best.h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#xA0;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ');const cal=Number(text.match(/Calories\s+(\d+)/i)?.[1]),fat=Number(text.match(/Total Fat\s+(\d+(?:\.\d+)?)g/i)?.[1]),carbs=Number(text.match(/Total Carbohydrate\s+(\d+(?:\.\d+)?)g/i)?.[1]),protein=Number(text.match(/Protein\s+(\d+(?:\.\d+)?)g/i)?.[1]),serving=text.match(/Serving Size\s+(.{1,80}?)(?=Amount Per Serving|Calories)/i)?.[1]?.trim();if(Number.isFinite(cal)&&Number.isFinite(protein))return item(best.title,'H-E-B',cal,protein,Number.isFinite(carbs)?carbs:0,Number.isFinite(fat)?fat:0,HEB_SOURCE,best.productUrl,'High',{servingSize:serving||null,retrievedAt:new Date().toISOString(),matchScore:best.score})}}}catch{}
 // Never silently log a random USDA/H-E-B result for an H-E-B branded request. A wrong food is worse than asking for more detail.
 return null}
export async function POST(req){try{const{query}=await req.json(),q=String(query||'').trim();if(!q)return NextResponse.json({error:'Missing meal description'},{status:400});const known=parseKnown(q);if(known.items.length)return NextResponse.json({items:known.items,notes:known.notes,clarifications:known.clarifications,parsedFrom:q,sourceStrategy:'Verified product match'});
 if(isHeb(q)){const food=await hebLookup(q);if(food)return NextResponse.json({items:[food],notes:['Matched the H-E-B product by product-name keywords and read its nutrition facts.'],parsedFrom:q,sourceStrategy:'H-E-B official product page'});return NextResponse.json({error:'I could not confidently match that exact H-E-B product, so I did not log a random item. Add the exact product/flavor or package size.'},{status:404})}
 const cleaned=q.replace(/^(i\s+(had|ate|got)|i just (had|ate|got)|for breakfast i had|for lunch i had|for dinner i had)\s+/i,'').replace(/\s+(after|before)\s+(the\s+)?gym.*$/i,'').replace(/\s+(for breakfast|for lunch|for dinner).*$/i,'').trim();const food=await usda(cleaned);if(food)return NextResponse.json({items:[food],notes:['No verified restaurant-specific match was found, so USDA FoodData Central was used.'],parsedFrom:q,sourceStrategy:'USDA FoodData Central fallback'});return NextResponse.json({error:'I could not verify this meal yet. Include the restaurant/brand, exact item, size, and flavor when relevant.'},{status:404})}catch(e){return NextResponse.json({error:'Nutrition research failed. Please try again.'},{status:500})}}
