import { NextResponse } from 'next/server';
const USDA_API='https://api.nal.usda.gov/fdc/v1/foods/search';
const item=(name,brand,cal,protein,carbs,fat,source,sourceUrl,confidence='High',extra={})=>({name,brand,cal,protein,carbs,fat,source,sourceUrl,confidence,...extra});
const MCD_SOURCE="McDonald's official nutrition";
const MCD={mcgriddle:item('Sausage, Egg & Cheese McGriddles',"McDonald's",550,20,47,28,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/sausage-egg-cheese-mcgriddles.html'),refresher:item('Medium Strawberry Watermelon Refresher',"McDonald's",210,0,49,0,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/strawberry-watermelon-refresher-medium.html'),nuggets4:item('4 Piece Chicken McNuggets',"McDonald's",170,9,10,10,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/chicken-mcnuggets-4-piece.html'),smallFries:item('Small World Famous Fries',"McDonald's",230,3,31,11,MCD_SOURCE,'https://www.mcdonalds.com/us/en-us/product/small-french-fries.html')};
const WINGSTOP_SOURCE='Wingstop official nutrition guide',WINGSTOP_URL='https://s3.amazonaws.com/wingstop.com/assets/static/WSR18-0009-Corporate-NutritionalGuide-JumboWings-HR_OFFICAL.pdf';
const WS_SANDWICHES={plain:item('Chicken Sandwich - Plain','Wingstop',610,32,66,24,WINGSTOP_SOURCE,WINGSTOP_URL),atomic:item('Chicken Sandwich - Atomic','Wingstop',650,33,74,24,WINGSTOP_SOURCE,WINGSTOP_URL),cajun:item('Chicken Sandwich - Cajun','Wingstop',640,33,70,25,WINGSTOP_SOURCE,WINGSTOP_URL),'garlic parmesan':item('Chicken Sandwich - Garlic Parmesan','Wingstop',890,34,71,52,WINGSTOP_SOURCE,WINGSTOP_URL),hawaiian:item('Chicken Sandwich - Hawaiian','Wingstop',710,33,90,24,WINGSTOP_SOURCE,WINGSTOP_URL),'hickory smoked bbq':item('Chicken Sandwich - Hickory Smoked BBQ','Wingstop',730,34,96,24,WINGSTOP_SOURCE,WINGSTOP_URL),'lemon pepper':item('Chicken Sandwich - Lemon Pepper','Wingstop',850,32,67,50,WINGSTOP_SOURCE,WINGSTOP_URL),'louisiana rub':item('Chicken Sandwich - Louisiana Rub','Wingstop',790,32,67,43,WINGSTOP_SOURCE,WINGSTOP_URL),'mango habanero':item('Chicken Sandwich - Mango Habanero','Wingstop',740,32,94,24,WINGSTOP_SOURCE,WINGSTOP_URL),mild:item('Chicken Sandwich - Mild','Wingstop',870,32,67,52,WINGSTOP_SOURCE,WINGSTOP_URL),'original hot':item('Chicken Sandwich - Original Hot','Wingstop',630,32,68,25,WINGSTOP_SOURCE,WINGSTOP_URL),'spicy korean q':item('Chicken Sandwich - Spicy Korean Q','Wingstop',720,34,90,24,WINGSTOP_SOURCE,WINGSTOP_URL)};
const WS_FRIES=item('Seasoned Fries - Regular','Wingstop',500,8,69,21,WINGSTOP_SOURCE,WINGSTOP_URL),WS_RANCH=item('Ranch Dip','Wingstop',320,1,2,34,WINGSTOP_SOURCE,WINGSTOP_URL);
function nutrient(food,names){for(const n of food.foodNutrients||[]){const name=String(n.nutrientName||'').toLowerCase();if(names.some(x=>name.includes(x)))return Number(n.value||0)}return 0}
async function usda(query){const url=`${USDA_API}?api_key=${process.env.USDA_API_KEY||'DEMO_KEY'}&query=${encodeURIComponent(query)}&pageSize=10`;const res=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});if(!res.ok)return null;const data=await res.json(),foods=data.foods||[];if(!foods.length)return null;const low=query.toLowerCase();const food=foods.find(f=>`${f.brandOwner||''} ${f.brandName||''} ${f.description||''}`.toLowerCase().includes('h-e-b'))||foods[0];return item(food.description,food.brandOwner||food.brandName||'USDA',Math.round(nutrient(food,['energy'])),Math.round(nutrient(food,['protein'])),Math.round(nutrient(food,['carbohydrate'])),Math.round(nutrient(food,['total lipid','total fat'])),'USDA FoodData Central',`https://fdc.nal.usda.gov/fdc-app.html#/food-details/${food.fdcId}/nutrients`,'Medium',{fdcId:food.fdcId,query:low})}
function cleanText(q){return q.toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').trim()} function has(q,...terms){return terms.some(t=>q.includes(t))}
function wingstopFlavor(q){const aliases=[['garlic parmesan',['garlic parmesan','garlic parm']],['hickory smoked bbq',['hickory smoked bbq','hickory bbq','bbq']],['lemon pepper',['lemon pepper']],['louisiana rub',['louisiana rub']],['mango habanero',['mango habanero']],['original hot',['original hot']],['spicy korean q',['spicy korean q','korean q']],['atomic',['atomic']],['cajun',['cajun']],['hawaiian',['hawaiian']],['mild',['mild']],['plain',['plain','no sauce','unseasoned']]];for(const [key,words] of aliases)if(words.some(w=>q.includes(w)))return key;return null}
function parseKnown(q){const low=cleanText(q),items=[],notes=[],clarifications=[];if(/sausage.*egg.*cheese.*mcgriddle|sausage egg and cheese mcgriddle|mcgriddle/.test(low))items.push(MCD.mcgriddle);if(/strawberry.*watermelon.*refresher/.test(low))items.push(MCD.refresher);if(/(?:4|four)[ -]?(?:piece|pc)?\s*(?:chicken\s*)?(?:mcnuggets|nuggets)/.test(low))items.push(MCD.nuggets4);if(/small\s+(?:world famous\s+)?(?:fry|fries)|(?:fry|fries)\s*(?:small)/.test(low))items.push(MCD.smallFries);if(low.includes('wingstop')){const sandwichMention=has(low,'chicken sandwich','sandwich');if(sandwichMention){const flavor=wingstopFlavor(low);if(flavor)items.push(WS_SANDWICHES[flavor]);else{items.push({...WS_SANDWICHES.plain,confidence:'Medium',assumption:'No Wingstop flavor was specified, so this was logged as Plain.'});notes.push('Wingstop sandwich flavor changes calories a lot. Logged Plain because no flavor was specified.')}}if(has(low,'fries','seasoned fries','lemon pepper fries'))items.push(WS_FRIES);if(has(low,'ranch','ranch dip'))items.push(WS_RANCH);if(low.includes('combo')&&!has(low,'fries','seasoned fries'))items.push(WS_FRIES)}return{items,notes,clarifications}}
function isHeb(q){return /\b(h[ -]?e[ -]?b|heb|meal simple)\b/i.test(q)}
function hebSearchTerms(q){return q.replace(/\b(i\s+(had|ate|got|bought)|i just (had|ate|got|bought)|from|at|an?|the|some)\b/gi,' ').replace(/\b(h[ -]?e[ -]?b|heb)\b/gi,'H-E-B').replace(/\s+/g,' ').trim()}
async function hebLookup(query){
 const terms=hebSearchTerms(query);
 // H-E-B product pages expose Nutrition Facts in their rendered HTML. Search the official catalog first.
 const searchUrl=`https://www.heb.com/search/?q=${encodeURIComponent(terms.replace(/H-E-B/gi,'').trim())}`;
 try{
  const r=await fetch(searchUrl,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html'},cache:'no-store'});
  if(r.ok){const html=await r.text();
   const links=[...html.matchAll(/href=["']([^"']*\/product-detail\/[^"']+)["']/gi)].map(m=>m[1]);
   if(links.length){const productUrl=new URL(links[0],'https://www.heb.com').href;const p=await fetch(productUrl,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/html'},cache:'no-store'});if(p.ok){const h=await p.text();
    const text=h.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#xA0;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ');
    const title=(h.match(/<title>(.*?)<\/title>/i)?.[1]||terms).replace(/ - Shop[\s\S]*$/i,'').trim();
    const cal=Number(text.match(/Calories\s+(\d+)/i)?.[1]);const fat=Number(text.match(/Total Fat\s+(\d+(?:\.\d+)?)g/i)?.[1]);const carbs=Number(text.match(/Total Carbohydrate\s+(\d+(?:\.\d+)?)g/i)?.[1]);const protein=Number(text.match(/Protein\s+(\d+(?:\.\d+)?)g/i)?.[1]);
    const serving=text.match(/Serving Size\s+(.{1,80}?)(?=Amount Per Serving|Calories)/i)?.[1]?.trim();
    if(Number.isFinite(cal)&&Number.isFinite(protein))return item(title,'H-E-B',cal,protein,Number.isFinite(carbs)?carbs:0,Number.isFinite(fat)?fat:0,'H-E-B official product nutrition',productUrl,'High',{servingSize:serving||null,retrievedAt:new Date().toISOString()});
   }}
  }
 }catch{}
 const fallback=await usda(`H-E-B ${terms.replace(/H-E-B/gi,'')}`);if(fallback)return {...fallback,confidence:'Medium',sourceStrategy:'H-E-B official catalog unavailable; USDA fallback'};return null;
}
export async function POST(req){try{const{query}=await req.json(),q=String(query||'').trim();if(!q)return NextResponse.json({error:'Missing meal description'},{status:400});const known=parseKnown(q);if(known.items.length)return NextResponse.json({items:known.items,notes:known.notes,clarifications:known.clarifications,parsedFrom:q,sourceStrategy:'Official restaurant nutrition first'});
 if(isHeb(q)){const food=await hebLookup(q);if(food)return NextResponse.json({items:[food],notes:[food.source==='H-E-B official product nutrition'?'Matched against the H-E-B product catalog and read the product nutrition facts.':'No official H-E-B page could be parsed, so the closest H-E-B/USDA result was used.'],parsedFrom:q,sourceStrategy:food.source==='H-E-B official product nutrition'?'H-E-B official product page':'USDA fallback'});return NextResponse.json({error:'I could not identify that H-E-B item. Include the product name/flavor and package or serving size if you know it.'},{status:404})}
 const cleaned=q.replace(/^(i\s+(had|ate|got)|i just (had|ate|got)|for breakfast i had|for lunch i had|for dinner i had)\s+/i,'').replace(/\s+(after|before)\s+(the\s+)?gym.*$/i,'').replace(/\s+(for breakfast|for lunch|for dinner).*$/i,'').trim();const food=await usda(cleaned);if(food)return NextResponse.json({items:[food],notes:['No verified restaurant-specific match was found, so USDA FoodData Central was used.'],parsedFrom:q,sourceStrategy:'USDA FoodData Central fallback'});return NextResponse.json({error:'I could not verify this meal yet. Include the restaurant/brand, exact item, size, and flavor when relevant.'},{status:404})}catch(e){return NextResponse.json({error:'Nutrition research failed. Please try again.'},{status:500})}}
