'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
const TARGET={cal:3000,protein:150,carbs:375,fat:100};
const dayKey=()=>new Date().toISOString().slice(0,10); const sum=(a,k)=>a.reduce((n,x)=>n+(Number(x[k])||0),0); const JAPAN=new Date('2026-12-30T00:00:00');
export default function Home(){
 const [meals,setMeals]=useState([]),[weights,setWeights]=useState([]),[sets,setSets]=useState([]),[targets,setTargets]=useState(TARGET),[mealText,setMealText]=useState(''),[weightInput,setWeightInput]=useState(''),[hydrated,setHydrated]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const g=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};setMeals(g('htc-meals',[]));setWeights(g('htc-weights',[]));setSets(g('htc-sets',[]));setTargets(g('htc-targets',TARGET));setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;localStorage.setItem('htc-meals',JSON.stringify(meals));localStorage.setItem('htc-weights',JSON.stringify(weights));localStorage.setItem('htc-sets',JSON.stringify(sets));localStorage.setItem('htc-targets',JSON.stringify(targets))},[meals,weights,sets,targets,hydrated]);
 const today=useMemo(()=>meals.filter(x=>x.day===dayKey()),[meals]); const totals={cal:sum(today,'cal'),protein:sum(today,'protein'),carbs:sum(today,'carbs'),fat:sum(today,'fat')}; const remain={cal:Math.max(0,targets.cal-totals.cal),protein:Math.max(0,targets.protein-totals.protein),carbs:Math.max(0,targets.carbs-totals.carbs),fat:Math.max(0,targets.fat-totals.fat)}; const countdown=Math.max(0,Math.ceil((JAPAN-new Date())/86400000));
 function resetToday(){if(!today.length){setMessage('Today is already at zero.');return}if(!confirm(`Reset today? This will remove ${today.length} logged food item${today.length===1?'':'s'} from today only.`))return;setMeals(v=>v.filter(x=>x.day!==dayKey()));setMessage('Today reset to 0 calories. Previous days were not changed.')}
 function addWeight(){const value=Number(weightInput);if(!value)return;setWeights(v=>[...v,{id:Date.now(),value,day:dayKey(),date:new Date().toLocaleDateString()}]);setWeightInput('')}
 return <div className="simpleApp"><header className="simpleHeader"><div><span>精神と時の部屋 · seishin to toki no heya</span><h1>HYPERBOLIC TIME CHAMBER</h1><p>KAIZEN // JAPAN BULK PROTOCOL</p></div><div className="days"><b>{countdown}</b><small>DAYS TO JAPAN</small></div></header>
 <nav className="simpleNav"><a href="#today">TODAY</a><a href="#meals">MEALS</a><a href="#progress">PROGRESS</a><Link href="/history">HISTORY</Link></nav>
 <main>
  <section id="today" className="panel pagePanel"><div className="sectionTitle"><div><span className="eyebrow">TODAY // {dayKey()}</span><h2>DAILY FUEL</h2></div><button className="dangerButton" onClick={resetToday}>RESET TODAY</button></div><div className="reportHero"><div><small>CALORIES</small><b>{totals.cal} / {targets.cal}</b></div><div><small>PROTEIN</small><b>{totals.protein}g / {targets.protein}g</b></div><div><small>CARBS</small><b>{totals.carbs}g / {targets.carbs}g</b></div><div><small>FAT</small><b>{totals.fat}g / {targets.fat}g</b></div></div><div className="needPanel"><span className="eyebrow">YOU STILL NEED</span><div className="needNums"><b>{remain.cal}<small> kcal</small></b><b>{remain.protein}<small>g protein</small></b></div><p>{remain.carbs}g carbs · {remain.fat}g fat remaining</p></div>{message&&<div className="systemMsg">SYSTEM // {message}</div>}</section>
  <section id="meals" className="panel pagePanel"><span className="eyebrow">PLAIN ENGLISH MEAL LOGGER</span><h2>TELL IT WHAT YOU ATE</h2><p className="subcopy">Write normally. Example: “I got a Wingstop lemon pepper chicken sandwich with regular fries after the gym.” The app researches and labels the individual foods for you.</p><div className="commandBox"><textarea value={mealText} onChange={e=>setMealText(e.target.value)} placeholder="I had a sausage egg and cheese McGriddle and a medium strawberry watermelon refresher after the gym"/><button>RESEARCH + LOG</button></div><div className="mealList">{today.length?today.map(m=><article key={m.id}><div><b>{m.name||m.raw}</b><span>{m.brand||'Food'} · {m.source||'Nutrition research'} · {m.confidence||'Medium'} confidence</span>{m.raw&&<span>YOU SAID: “{m.raw}”</span>}</div><div className="mealMacros"><strong>{m.cal}</strong><small>kcal</small><strong>{m.protein}g</strong><small>protein</small></div><button onClick={()=>setMeals(v=>v.filter(x=>x.id!==m.id))}>×</button></article>):<p className="empty">Nothing logged today.</p>}</div></section>
  <section id="progress" className="panel pagePanel"><span className="eyebrow">BODYWEIGHT</span><h2>PROGRESS</h2><div className="weightEntry"><input inputMode="decimal" value={weightInput} onChange={e=>setWeightInput(e.target.value)} placeholder="Today's weight (lb)"/><button onClick={addWeight}>LOG WEIGHT</button></div><div className="weightHistory">{weights.slice(-7).reverse().map(w=><div key={w.id}><span>{w.date}</span><b>{Number(w.value).toFixed(1)} lb</b></div>)}</div><Link className="historyLink" href="/history">OPEN FULL CHAMBER HISTORY →</Link></section>
 </main><footer><b>かいぜん — KAIZEN</b><span>SMALL IMPROVEMENTS. EVERY DAY.</span></footer></div>
}
